feature: ホーム画面のボタンと購入トッピングのベースデザイン作成
prismistim/povo-topping-manager pull request #36
Opened 2021-12-08 09:06 UTC by ShoContain

2021-12-08 12:05 UTC, prismistim requested changes
ボタンの色に関してはその黄色ではないので、 povo のテーマカラーをtailwindのテーマとして入れようと思います

2021-12-08 12:05 UTC, prismistim commented on src/components/organisms/home/ToppingListHistory.vue
> +const props = defineProps({
この辺りはいつもの開発と同様、type・required・defaultを定義した方がよさそうですね
解読しやすいコードになるうえ、万が一値が入らなかった場合、初期値を固定することができるので

2021-12-08 12:05 UTC, prismistim commented on src/components/organisms/home/ToppingListHistory.vue
> +          >HRとは</a
prettierの整形が意図しない感じになってるので
```
<a
  ...
>
  ...
</a>
```
となるよう修正してもらえますか？

2021-12-08 12:05 UTC, prismistim commented on src/components/organisms/home/AddBtn.vue
> +      class="w-40 h-40 bg-yellow-300 text-lg rounded-full hover:bg-yellow-400 shadow-md font-mono"
細かいですが、hover時のクラスを指定する際、同種のクラスの隣に持ってくるといいと思います

2021-12-08 12:05 UTC, prismistim commented on src/components/organisms/home/AddBtn.vue
> +<script setup lang="ts"></script>
不要であれば消してください

2021-12-09 03:56 UTC, ShoContain commented
プレビューありがとう。修正後再度PRします。

2021-12-12 15:08 UTC, closed without merging