Feature/add register button
prismistim/povo-topping-manager pull request #40
Opened 2021-12-12 15:10 UTC by ShoContain

2021-12-13 13:37 UTC, prismistim requested changes
とりあえず見ました。
- withDefaults はいいと思ったんですけど、そもそも props を別に型を定義するかしないかとか決めたほうがいいですね。
- あとはinterfaceとtype問題
  - https://zenn.dev/luvmini511/articles/6c6f69481c2d17

2021-12-13 13:37 UTC, prismistim commented on src/components/organisms/home/ToppingListHistory.vue
> +const props = withDefaults(defineProps<Props>(), {
withDefaults 初めて見ましたけど、これ使うとpropsのプロパティがnullでも通ってしまうので少し気になる

2021-12-13 13:37 UTC, prismistim commented on src/components/atoms/FormDefault.vue
> +<script setup lang="ts">
?

2021-12-13 13:37 UTC, prismistim commented on src/components/organisms/home/ToppingListHistory.vue
> +const props = withDefaults(defineProps<Props>(), {
? 消せばいいのかな

2021-12-18 03:10 UTC, prismistim commented on src/components/atoms/FormDefault.vue
> +<script setup lang="ts">
これ消せますか？

2021-12-18 03:45 UTC, ShoContain commented on src/components/atoms/FormDefault.vue
> +<script setup lang="ts">
これ木村くんの練習用に書いてるのかと思った

2021-12-18 03:49 UTC, prismistim commented on src/components/atoms/FormDefault.vue
> +<script setup lang="ts">
単純に使わないファイルなら消しておいてほしいと思っただけですw

2021-12-18 03:52 UTC, ShoContain commented on src/components/atoms/FormDefault.vue
> +<script setup lang="ts">
削除したお

2021-12-18 03:53 UTC, prismistim approved these changes

2021-12-18 03:56 UTC, merged