feat: 購入したトッピングリストのデザイン調整
prismistim/povo-topping-manager pull request #41
Opened 2021-12-18 06:04 UTC by ShoContain

2021-12-21 07:48 UTC, prismistim requested changes
余力あれば汎用化までお願いします！

2021-12-21 07:48 UTC, prismistim commented on src/components/organisms/home/ToppingListHistory.vue
> +          <p class="font-mono pl-6 py-2 pr-6">データ追加３GB（30日間）</p>
ここら辺良かったらv-forで実装しておいても良いかもです

2021-12-21 15:21 UTC, ShoContain commented on src/components/organisms/home/ToppingListHistory.vue
> +          <p class="font-mono pl-6 py-2 pr-6">データ追加３GB（30日間）</p>
ok

2021-12-22 12:11 UTC, prismistim approved these changes

2021-12-23 08:12 UTC, merged