feat: 購入登録画面のルーティング追加
prismistim/povo-topping-manager pull request #42
Opened 2021-12-18 09:21 UTC by ShoContain

2021-12-21 07:58 UTC, prismistim requested changes
router に関しては script setup 内で完結させてる今の環境だとどちらでもいいかもしれませんが、useRouter使ってみてください

2021-12-21 07:58 UTC, prismistim commented on src/components/organisms/home/AddBtn.vue
> +
```js
import { useRouter } from 'vue-router'

const router = useRouter()
```
の方が良いかも？

2021-12-21 07:58 UTC, prismistim commented on src/components/pages/Home.vue
> +      <AddBtn path="/add" />
AddBtnにも書きましたが、汎用性なくてもいいかもです

2021-12-21 08:05 UTC, prismistim commented on src/components/pages/Add.vue
> +<script setup lang="ts">
@kimkim0814 Addのpageを作ってもらったのでこれをもとに作って行ってもいいかも？

2021-12-21 14:36 UTC, ShoContain commented on src/components/organisms/home/AddBtn.vue
> +    <router-link to="add">
/addを動的ルーティングにすること現状ないんでrouter-linkでいい気がしたんで、router-link使った

2021-12-22 12:09 UTC, prismistim approved these changes

2021-12-23 08:10 UTC, merged